// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIfT7gdL4EO4YlLf8HQHUPJfDd6nKTmN4',
    appId: '1:778592409323:web:9b75b92526f5a7bcd6d0ae',
    messagingSenderId: '778592409323',
    projectId: 'istemanipal-1708a',
    authDomain: 'istemanipal-1708a.firebaseapp.com',
    storageBucket: 'istemanipal-1708a.firebasestorage.app',
    measurementId: 'G-EBW8DKXJJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0O74SThlGiBAPiMz7HzF7E9hLoNtQXes',
    appId: '1:778592409323:android:80e8fbe265795ee2d6d0ae',
    messagingSenderId: '778592409323',
    projectId: 'istemanipal-1708a',
    storageBucket: 'istemanipal-1708a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIsVB8mRq12ZOyGvb2UtO_O8dFTRDZj44',
    appId: '1:778592409323:ios:e0279d5ce7db21ddd6d0ae',
    messagingSenderId: '778592409323',
    projectId: 'istemanipal-1708a',
    storageBucket: 'istemanipal-1708a.firebasestorage.app',
    iosClientId: '778592409323-r224625i0stkdq33hf93n0sjmp199dvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.isteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIsVB8mRq12ZOyGvb2UtO_O8dFTRDZj44',
    appId: '1:778592409323:ios:e0279d5ce7db21ddd6d0ae',
    messagingSenderId: '778592409323',
    projectId: 'istemanipal-1708a',
    storageBucket: 'istemanipal-1708a.firebasestorage.app',
    iosClientId: '778592409323-r224625i0stkdq33hf93n0sjmp199dvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.isteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIfT7gdL4EO4YlLf8HQHUPJfDd6nKTmN4',
    appId: '1:778592409323:web:dfbe46a531d723ecd6d0ae',
    messagingSenderId: '778592409323',
    projectId: 'istemanipal-1708a',
    authDomain: 'istemanipal-1708a.firebaseapp.com',
    storageBucket: 'istemanipal-1708a.firebasestorage.app',
    measurementId: 'G-QXWWSH1SNN',
  );
}
